- project:
    name: Juniper/contrail-helm-deployer
    check:
      jobs:
        - zuul-jobs-linters
    experimental:
      jobs:
        - contrail-sanity-ubuntu1604-helm-ocata
          voting: false
