- project:
    name: Juniper/contrail-helm-deployer
    check:
      jobs:
        - zuul-jobs-linters
        - contrail-sanity-ubuntu1604-helm-ocata:
            dependencies:
              - contrail-vnc-build-containers-centos7-ocata
              - contrail-vnc-build-test-containers
            voting: false
    experimental:
      jobs:
        - contrail-sanity-ubuntu1604-helm-ocata:
            voting: false
            vars:
              contrail_docker_registry: opencontrailnightly
              container_tag: ocata-master-157
