---
# TODO: get deployment type automatically using inventory
- name: set deployment type
  set_fact:
    deploy_type: multi_node

- name: deploy openstack helm charts
  include: "{{ deploy_type }}.yaml"
  when: deploy_type == "multi_node" or deploy_type == "single_node"

- name: wait for openstack pods to come up
  shell: ./tools/deployment/common/wait-for-pods.sh openstack 1800
  args:
    chdir: "{{ osh_dir }}"
