{{- if not .Values.manifests.each_container_is_pod }}
{{- if .Values.manifests.daemonset_analytics }}
{{- $context := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analytics
spec:
  template:
    metadata:
      labels:
{{ tuple $context "opencontrail" "contrail-analytics" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.analytics.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.analytics.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
{{ tuple $context .Values.dependencies.analytics nil | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
      - name: contrail-analytics-api
        image: {{ .Values.images.tags.analytics_api | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-analytics
        - configMapRef:
            name: configmap-analytics-auth
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
      - name: contrail-collector
        image: {{ .Values.images.tags.contrail_collector | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-analytics
        - configMapRef:
            name: configmap-analytics-auth
        - configMapRef:
            name: configmap-analytics-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
      - name: contrail-alarm-gen
        image: {{ .Values.images.tags.analytics_alarm_gen | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-analytics
        - configMapRef:
            name: configmap-analytics-auth
        - configMapRef:
            name: configmap-analytics-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
      - name: contrail-query-engine
        image: {{ .Values.images.tags.analytics_query_engine | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-analytics
        - configMapRef:
            name: configmap-analytics-auth
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
      - name: contrail-snmp-collector
        image: {{ .Values.images.tags.analytics_snmp_collector | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-analytics
        - configMapRef:
            name: configmap-analytics-auth
        - configMapRef:
            name: configmap-analytics-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
      - name: contrail-topology
        image: {{ .Values.images.tags.contrail_topology | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-analytics
        - configMapRef:
            name: configmap-analytics-auth
        - configMapRef:
            name: configmap-analytics-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
      - name: contrail-analytics-nodemgr
        image: {{ .Values.images.tags.nodemgr | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-analytics
        - configMapRef:
            name: configmap-analytics-auth
        env:
        - name: NODE_TYPE
          value: analytics
        - name: DOCKER_HOST
          value: "unix://mnt/docker.sock"
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
# todo: there is type Socket in new kubernetes, it is possible to use full
# path:
# hostPath:
#   path: /var/run/docker.sock and
#   type: Socket
        volumeMounts:
        - mountPath: /mnt
          name: docker-unix-socket
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run
      - name: etc-contrail
        hostPath:
          path: /etc/contrail/analytics/
      - name: contrail-log
        hostPath:
          path: /var/log/contrail/analytics/

{{- end }}
{{- end }}
