{{- $_ := set .Values "images" .Values.global.images }}
{{- if .Values.manifests.daemonset_analytics }}
{{- $context := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analytics
spec:
{{ tuple $context "analytics" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $context "opencontrail" "contrail-analytics" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-hash: {{ tuple "configmap-env.yaml" $context | include "helm-toolkit.utils.hash" }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.analytics.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.analytics.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: contrail-analytics-docker-secret
      initContainers:
{{ tuple $context .Values.dependencies.analytics nil | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: contrail-node-init
          image: {{ .Values.global.images.tags.node_init | quote }}
          imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          env:
          - name: CONTRAIL_STATUS_IMAGE
            value: {{ .Values.global.images.tags.contrail_status | quote }}
          envFrom:
          - configMapRef:
              name: contrail-analytics-env
          volumeMounts:
          - mountPath: /host/usr/bin
            name: host-usr-bin
          - mountPath: /etc/contrail/ssl
            name: ssl-dir
          - mountPath: /etc/sysctl.conf
            name: host-sysctl-conf
      containers:
      - name: contrail-analytics-api
        image: {{ .Values.global.images.tags.analytics_api | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        ports:
        - name: api-port
          containerPort: {{ .Values.global.contrail_env.ANALYTICS_API_PORT | default 8081 }}
        - name: introspect-port
          containerPort: {{ .Values.global.contrail_env.ANALYTICS_API_INTROSPECT_PORT | default 8090 }}
        envFrom:
        - configMapRef:
            name: contrail-analytics-env
        - configMapRef:
            name: contrail-analytics-keystone
        env:
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /var/crashes
          name: var-crashes-analytics
        - mountPath: /etc/contrail/ssl
          name: ssl-dir
      - name: contrail-collector
        image: {{ .Values.global.images.tags.contrail_collector | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-analytics-env
        - configMapRef:
            name: contrail-analytics-keystone
        - configMapRef:
            name: contrail-analytics-rabbitmq
        env:
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /var/crashes
          name: var-crashes-analytics
      - name: contrail-alarm-gen
        image: {{ .Values.global.images.tags.analytics_alarm_gen | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-analytics-env
        - configMapRef:
            name: contrail-analytics-keystone
        - configMapRef:
            name: contrail-analytics-rabbitmq
        env:
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /var/crashes
          name: var-crashes-analytics
      - name: contrail-query-engine
        image: {{ .Values.global.images.tags.analytics_query_engine | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-analytics-env
        - configMapRef:
            name: contrail-analytics-keystone
        env:
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /var/crashes
          name: var-crashes-analytics
      - name: contrail-snmp-collector
        image: {{ .Values.global.images.tags.analytics_snmp_collector | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-analytics-env
        - configMapRef:
            name: contrail-analytics-keystone
        - configMapRef:
            name: contrail-analytics-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /var/crashes
          name: var-crashes-analytics
      - name: contrail-topology
        image: {{ .Values.global.images.tags.contrail_topology | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-analytics-env
        - configMapRef:
            name: contrail-analytics-keystone
        - configMapRef:
            name: contrail-analytics-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /var/crashes
          name: var-crashes-analytics
      - name: contrail-analytics-nodemgr
        image: {{ .Values.global.images.tags.nodemgr | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-analytics-env
        - configMapRef:
            name: contrail-analytics-keystone
        env:
        - name: NODE_TYPE
          value: analytics
        - name: DOCKER_HOST
          value: "unix://mnt/docker.sock"
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /var/crashes
          name: var-crashes-analytics
        - mountPath: /mnt/docker.sock
          name: docker-unix-socket
        - mountPath: /etc/contrail/ssl
          name: ssl-dir
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: contrail-log
        hostPath:
          path: /var/log/contrail
      - name: var-crashes-analytics
        hostPath:
          path: /var/crashes
      - name: host-usr-bin
        hostPath:
          path: {{ .Values.volumeMounts.host_usr_bin.hostPath }}
      - name: ssl-dir
        hostPath:
          path: /etc/contrail/ssl
      - name: host-sysctl-conf
        hostPath:
          path: /etc/sysctl.conf
{{- end }}
