{{- if .Values.manifests.ingress_analytics_api }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $val := .Values.ingress.analytics_api.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: contrail-analytics-api
spec:
  rules:
  {{- range .Values.ingress.analytics_api.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - backend:
          serviceName: analytics-api-server
          servicePort: api
        path: {{ .path }}
  {{- end }}
{{- end }}
