{{- $context := . }}
{{- $keystone_auth_host := tuple "keystone" "internal" $context | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" }}
{{- $rabbitmq_host := tuple "rabbitmq" "internal" $context | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" }}

{{- if empty .Values.global.contrail_env.IPFABRIC_SERVICE_HOST -}}
{{- tuple "nova_metadata" "internal" $context | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" | set .Values.global.contrail_env "IPFABRIC_SERVICE_HOST" | quote | trunc 0 -}}
{{- end -}}

{{- if empty .Values.global.contrail_env.IPFABRIC_SERVICE_PORT }}
{{- tuple "nova_metadata" "internal" "metadata" . | include "helm-toolkit.endpoints.endpoint_port_lookup" | set .Values.global.contrail_env "IPFABRIC_SERVICE_PORT" | quote | trunc 0 -}}
{{- end -}}

{{- if empty .Values.global.contrail_env.networkManager_ip -}}
{{- tuple "network" "internal" $context | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" | set .Values.global.contrail_env "networkManager_ip" | quote | trunc 0 -}}
{{- end -}}

{{- if empty .Values.global.contrail_env.networkManager_port -}}
{{- tuple "network" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" | set .Values.global.contrail_env "networkManager_port" | quote | trunc 0 -}}
{{- end -}}

{{- if empty .Values.global.contrail_env.imageManager_ip -}}
{{- tuple "image" "internal" $context | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" | set .Values.global.contrail_env "imageManager_ip" | quote | trunc 0 -}}
{{- end -}}

{{- if empty .Values.global.contrail_env.imageManager_port -}}
{{- tuple "image" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" | set .Values.global.contrail_env "imageManager_port" | quote | trunc 0 -}}
{{- end -}}

{{- if empty .Values.global.contrail_env.computeManager_ip -}}
{{- tuple "nova" "internal" $context | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" | set .Values.global.contrail_env "computeManager_ip" | quote | trunc 0 -}}
{{- end -}}

{{- if empty .Values.global.contrail_env.computeManager_port -}}
{{- tuple "nova" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" | set .Values.global.contrail_env "computeManager_port" | quote | trunc 0 -}}
{{- end -}}

{{- if empty .Values.global.contrail_env.storageManager_ip -}}
{{- tuple "volume" "internal" $context | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" | set .Values.global.contrail_env "storageManager_ip" | quote | trunc 0 -}}
{{- end -}}

{{- if empty .Values.global.contrail_env.storageManager_port -}}
{{- tuple "volume" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" | set .Values.global.contrail_env "storageManager_port" | quote | trunc 0 -}}
{{- end -}}

{{- if .Values.manifests.configmap_controller_env }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-controller-env
data:
  {{- range $key, $value := .Values.global.contrail_env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  IPFABRIC_SERVICE_HOST: {{ .Values.global.contrail_env.IPFABRIC_SERVICE_HOST }}
  IPFABRIC_SERVICE_PORT: {{ .Values.global.contrail_env.IPFABRIC_SERVICE_PORT }}
  networkManager_ip: {{ .Values.global.contrail_env.networkManager_ip }}
  networkManager_port: {{ .Values.global.contrail_env.networkManager_port }}
  imageManager_ip: {{ .Values.global.contrail_env.imageManager_ip }}
  imageManager_port: {{ .Values.global.contrail_env.imageManager_port }}
  computeManager_ip: {{ .Values.global.contrail_env.computeManager_ip }}
  computeManager_port: {{ .Values.global.contrail_env.computeManager_port }}
  storageManager_ip: {{ .Values.global.contrail_env.storageManager_ip }}
  storageManager_port: {{ .Values.global.contrail_env.storageManager_port }}
  identityManager_apiVersion: {{ .Values.global.contrail_env.identityManager_apiVersion | default "['v3']" }}

{{- end }}

{{- if .Values.manifests.configmap_controller_keystone }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-controller-keystone
data:
  KEYSTONE_AUTH_ADMIN_USER: {{ .Values.endpoints.keystone.auth.username }}
  KEYSTONE_AUTH_ADMIN_TENANT: {{ .Values.endpoints.keystone.auth.project_name }}
  KEYSTONE_AUTH_ADMIN_PASSWORD: {{ .Values.endpoints.keystone.auth.password }}
  KEYSTONE_AUTH_USER_DOMAIN_NAME: {{ .Values.endpoints.keystone.auth.user_domain_name }}
  KEYSTONE_AUTH_PROJECT_DOMAIN_NAME: {{ .Values.endpoints.keystone.auth.project_domain_name }}
  KEYSTONE_AUTH_URL_VERSION: {{ .Values.endpoints.keystone.path.default }}
  KEYSTONE_AUTH_HOST: {{ $keystone_auth_host }}
  KEYSTONE_AUTH_PROTO: {{ .Values.endpoints.keystone.scheme.default }}
  KEYSTONE_AUTH_ADMIN_PORT: {{ .Values.endpoints.keystone.port.admin.default | quote }}
  KEYSTONE_AUTH_PUBLIC_PORT: {{ .Values.endpoints.keystone.port.api.default | quote }}
  KEYSTONE_AUTH_REGION_NAME: {{ .Values.endpoints.keystone.auth.region_name | quote }}
{{- end }}

{{- if .Values.manifests.configmap_controller_rabbitmq }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-controller-rabbitmq
data:
  RABBITMQ_NODES: {{ $rabbitmq_host }}
  RABBITMQ_PORT: {{ .Values.endpoints.rabbitmq.port.amqp.default | quote }}
  RABBITMQ_USER: {{ .Values.endpoints.rabbitmq.auth.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.endpoints.rabbitmq.auth.password | quote }}
  RABBITMQ_USE_SSL: {{ .Values.global.contrail_env.RABBITMQ_USE_SSL | default "false" | quote }}
  RABBITMQ_VHOST: {{ .Values.endpoints.rabbitmq.path | default "/" | quote }}
{{- end }}
