{{- if .Values.manifests.daemonset_control_only }}
{{- $context := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-control-only
spec:
  template:
    metadata:
      labels:
{{ tuple $context "opencontrail" "contrail-control-only" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.control_only.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.control_only.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
{{ tuple $context .Values.dependencies.control_only nil | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
      - name: contrail-control
        image: {{ .Values.images.tags.contrail_control | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-controller
        - configMapRef:
            name: configmap-controller-auth
        - configMapRef:
            name: configmap-controller-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
        - mountPath: /var/crashes
          name: var-crashes-control
      volumes:
      - name: etc-contrail
        hostPath:
          path: /etc/contrail/control/
      - name: contrail-log
        hostPath:
          path: /var/log/contrail/control/
      - name: var-crashes-control
        hostPath:
          path: /var/crashes/contrail/control
{{- end }}
