{{- if .Values.manifests.daemonset_control }}
{{- $_ := set .Values "images" .Values.global.images }}
{{- $context := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-control
spec:
{{ tuple $context "control" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $context "opencontrail" "contrail-control" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-hash: {{ tuple "configmap-env.yaml" $context | include "helm-toolkit.utils.hash" }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.control.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.control.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: contrail-controller-docker-secret
      initContainers:
{{ tuple $context .Values.dependencies.control nil | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: contrail-node-init
          image: {{ .Values.global.images.tags.node_init | quote }}
          imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          env:
          - name: CONTRAIL_STATUS_IMAGE
            value: {{ .Values.global.images.tags.contrail_status | quote }}
          envFrom:
          - configMapRef:
              name: contrail-controller-env
          volumeMounts:
          - mountPath: /host/usr/bin
            name: host-usr-bin
          - mountPath: /etc/contrail/ssl
            name: ssl-dir
          - mountPath: /etc/sysctl.conf
            name: host-sysctl-conf
      containers:
      - name: contrail-control
        image: {{ .Values.global.images.tags.contrail_control | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-controller-env
        - configMapRef:
            name: contrail-controller-keystone
        - configMapRef:
            name: contrail-controller-rabbitmq
        env:
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /var/crashes
          name: var-crashes-control
        - mountPath: /etc/contrail/ssl
          name: ssl-dir
      - name: contrail-dns
        image: {{ .Values.global.images.tags.control_dns | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-controller-env
        - configMapRef:
            name: contrail-controller-keystone
        - configMapRef:
            name: contrail-controller-rabbitmq
        env:
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/dns/
          name: etc-contrail-dns
        - mountPath: /var/crashes
          name: var-crashes-control
      - name: contrail-named
        image: {{ .Values.global.images.tags.control_named | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: contrail-controller-env
        - configMapRef:
            name: contrail-controller-keystone
        - configMapRef:
            name: contrail-controller-rabbitmq
        env:
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/dns/
          name: etc-contrail-dns
        - mountPath: /var/crashes
          name: var-crashes-control
      - name: contrail-control-nodemgr
        image: {{ .Values.global.images.tags.nodemgr | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-controller-env
        - configMapRef:
            name: contrail-controller-keystone
        env:
        - name: NODE_TYPE
          value: control
        - name: DOCKER_HOST
          value: "unix://mnt/docker.sock"
        - name: KEYSTONE_AUTH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.keystone.admin }}
              key: KEYSTONE_AUTH_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /mnt/docker.sock
          name: docker-unix-socket
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /var/crashes
          name: var-crashes-control
        - mountPath: /etc/contrail/ssl
          name: ssl-dir
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: etc-contrail-dns
        emptyDir: {}
      - name: contrail-log
        hostPath:
          path: /var/log/contrail
      - name: var-crashes-control
        hostPath:
          path: /var/crashes
      - name: host-usr-bin
        hostPath:
          path: {{ .Values.volumeMounts.host_usr_bin.hostPath }}
      - name: ssl-dir
        hostPath:
          path: /etc/contrail/ssl
      - name: host-sysctl-conf
        hostPath:
          path: /etc/sysctl.conf
{{- end }}
