{{- if .Values.manifests.daemonset_webui }}
{{- $context := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-webui
spec:
  template:
    metadata:
      labels:
{{ tuple $context "opencontrail" "contrail-webui" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.webui.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.webui.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
{{ tuple $context .Values.dependencies.webui nil | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
      - name: contrail-webui-middleware
        image: {{ .Values.images.tags.webui_middleware | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        ports:
        - name: http-port
          containerPort: {{ .Values.contrail_env.WEBUI_HTTP_LISTEN_PORT | default 8080 }}
        - name: https-port
          containerPort: {{ .Values.contrail_env.WEBUI_HTTPS_LISTEN_PORT | default 8143 }}
        envFrom:
        - configMapRef:
            name: configmap-controller
        - configMapRef:
            name: configmap-controller-auth
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
        - mountPath: /var/crashes
          name: var-crashes-webui
      - name: contrail-webui
        image: {{ .Values.images.tags.webui | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-controller
        - configMapRef:
            name: configmap-controller-auth
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
        - mountPath: /var/crashes
          name: var-crashes-webui
      volumes:
      - name: etc-contrail
        hostPath:
          path: /etc/contrail/webui/
      - name: contrail-log
        hostPath:
          path: /var/log/contrail/webui/
      - name: var-crashes-webui
        hostPath:
          path: /var/crashes/contrail/webui
{{- end }}
