{{- if .Values.manifests.ingress_config_api }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $val := .Values.ingress.config_api.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: contrail-config-api
spec:
  rules:
  {{- range .Values.ingress.config_api.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - backend:
          serviceName: config-api-server
          servicePort: api
        path: {{ .path }}
  {{- end }}
{{- end }}
