{{- if .Values.manifests.ingress_webui }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $val := .Values.ingress.webui.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: contrail-webui
spec:
  tls:
  - hosts:
    {{- range .Values.ingress.webui.hosts }}
    - {{ .name }}
    {{- end }}
  rules:
  {{- range .Values.ingress.webui.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - backend:
          serviceName: contrail-web-controller
          servicePort: https
        path: {{ .path }}
  {{- end }}
{{- end }}
