{{- if and .Values.manifests.each_container_is_pod .Values.manifests.daemonset_dpdk }}
{{- $context := . }}
# host_os is a mandatory field
{{- $_ := required ".Values.node.host_os must be specified, valid values are ubuntu, centos" .Values.node.host_os }}
{{- $host_os := .Values.node.host_os }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-vrouter-agent-dpdk
spec:
  template:
    metadata:
      labels:
{{ tuple $context "opencontrail" "contrail-vrouter-agent-dpdk" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      #Disable affinity for single node setup
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.vrouter_agent_dpdk.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.vrouter_agent_dpdk.node_selector_value }}
      #Enable tolerations for single node setup
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
{{ tuple $context .Values.dependencies.vrouter_agent_dpdk nil | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: contrail-agent-init-dpdk
          image: {{ .Values.images.tags.agent_vrouter_init_kernel_dpdk | quote }}
          imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          envFrom:
          - configMapRef:
              name: configmap-vrouter
          - configMapRef:
              name: configmap-vrouter-auth
          volumeMounts:
          - mountPath: /usr/src
            name: usr-src
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /dev
            name: dev
          - mountPath: /var/run
            name: var-run
      containers:
        - name: contrail-vrouter-agent-dpdk
          image: {{ .Values.images.tags.agent_vrouter_dpdk | quote }}
          imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          envFrom:
          - configMapRef:
              name: configmap-vrouter
          - configMapRef:
              name: configmap-vrouter-auth
          volumeMounts:
          - mountPath: /dev
            name: device
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /var/run
            name: var-run
          - mountPath: /var/log/contrail
            name: contrail-log
        - name: contrail-vrouter-watchdog
          image: {{ .Values.images.tags.vrouter_watchdog | quote }}
          imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          envFrom:
          - configMapRef:
              name: configmap-vrouter
          - configMapRef:
              name: configmap-vrouter-auth
          volumeMounts:
          - mountPath: /dev
            name: device
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /var/run
            name: var-run
          - mountPath: /var/log/contrail
            name: contrail-log
          - mountPath: /etc
            name: etc
        - name: contrail-vrouter-agent
          image: {{ .Values.images.tags.agent_vrouter | quote }}
          imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          envFrom:
          - configMapRef:
              name: configmap-vrouter
          - configMapRef:
              name: configmap-vrouter-auth
          env:
          volumeMounts:
          - mountPath: /usr/src
            name: usr-src
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /var/lib/contrail/
            name: var-lib-contrail
          - mountPath: /var/log/contrail/
            name: contrail-log
          - mountPath: /etc/contrail/
            name: etc-contrail
          - mountPath: /var/run
            name: var-run
          - mountPath: /dev
            name: device
      volumes:
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: var-lib-contrail
        hostPath:
          path: /var/lib/contrail/
      - name: etc-contrail
        hostPath:
          path: /etc/contrail/vrouter/
      - name: contrail-log
        hostPath:
          path: /var/log/contrail/vrouter/
{{- end }}
