---
- name: clone openstack helm repos
  hosts: primary
  gather_facts: no
  roles:
    - { role: clone-openstack, when: clone_openstack | bool }
  vars:
    clone_openstack: yes

- name: copy openstack helm repos to all nodes
  hosts: all
  gather_facts: no
  roles:
    - copy-openstack
